POST http://localhost:3000/api/register_user
Content-Type: application/json

{
  "username": "fdsfsdf",
  "handle": "adasd",
  "email": "w@gmail.com",
  "password": "1234567890"
}

###

POST http://localhost:3000/api/is_verified
Content-Type: application/json

{
  "token": ""
}

###

POST http://localhost:3000/api/get_user
Content-Type: application/json

{
  "token": ""
}

### 
POST http://localhost:3000/api/login_user
Content-Type: application/json

{
  "email": "asdasd",
  "password": "asdfsadf"
}

###
POST http://localhost:3000/api/change_username
Content-Type: application/json

{
  "token": "",
  "username": "kokitoaaa"
}